# Generated by Django 2.1.7 on 2019-02-18 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('architecture', models.CharField(max_length=300)),
                ('developer_stack', models.CharField(max_length=300)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'types',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.ApplicationType'),
        ),
    ]
