# Generated by Django 2.1.7 on 2019-02-24 01:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_application_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('url_repository', models.CharField(max_length=250, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Application')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'browsers',
            },
        ),
        migrations.CreateModel(
            name='MobileSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'mobiles',
            },
        ),
        migrations.CreateModel(
            name='TechniqueTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'mobiles_so',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'tools',
            },
        ),
        migrations.AddField(
            model_name='techniquetest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Tool'),
        ),
    ]
