# Generated by Django 2.1.7 on 2019-02-24 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0003_auto_20190223_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test_level', models.CharField(choices=[('U', 'Unidad'), ('I', 'Integración'), ('S', 'Sistema'), ('A', 'Aceptación')], max_length=1)),
                ('objective', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.ApplicationVersion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
                'ordering': ['-create_at'],
            },
        ),
    ]
