# Generated by Django 2.1.7 on 2019-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_testplan_iterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('R', 'Registrado'), ('P', 'Programado'), ('E', 'Ejecutado')], default='R', max_length=1),
        ),
    ]
