# Generated by Django 2.1.7 on 2019-03-08 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0008_testplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('P', 'Programado'), ('E', 'En ejecución'), ('S', 'Exitoso'), ('F', 'Fallido')], default='P', max_length=1)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('execution_date', models.DateTimeField(default=datetime.datetime.now)),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.TestPlan')),
            ],
            options={
                'verbose_name': 'execution',
                'verbose_name_plural': 'executions',
                'ordering': ['-execution_date'],
            },
        ),
    ]
