# Generated by Django 2.1.7 on 2019-03-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_auto_20190311_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='script_file',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='technique_test',
        ),
        migrations.AddField(
            model_name='testplan',
            name='scripts',
            field=models.ManyToManyField(blank=True, to='strategy.ApplicationScript'),
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='browser',
        ),
        migrations.AddField(
            model_name='testplan',
            name='browser',
            field=models.ManyToManyField(blank=True, to='strategy.Browser'),
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='mobile_so',
        ),
        migrations.AddField(
            model_name='testplan',
            name='mobile_so',
            field=models.ManyToManyField(blank=True, to='strategy.MobileSO'),
        ),
    ]
