# Generated by Django 2.1.7 on 2019-03-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0011_auto_20190315_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='execute_immediately',
            field=models.BooleanField(default=True),
        ),
    ]
