# Generated by Django 2.1.7 on 2019-03-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0012_testplan_execute_immediately'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='browser',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationversion',
            unique_together={('version', 'url_repository')},
        ),
        migrations.AlterUniqueTogether(
            name='mobileso',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='techniquetest',
            unique_together={('name', 'tool')},
        ),
    ]
