# Generated by Django 2.1.7 on 2019-03-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0013_auto_20190316_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('R', 'Registrado'), ('P', 'Programado'), ('E', 'Ejecutado')], default='P', max_length=1),
        ),
    ]
