# Generated by Django 2.1.7 on 2019-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0017_testexecution_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquetest',
            name='function_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
