# Generated by Django 2.1.7 on 2019-04-27 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0019_stepimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrtTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_diff', models.CharField(max_length=500)),
                ('data', models.CharField(max_length=500)),
                ('step_image_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image1', to='strategy.StepImage')),
                ('step_image_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image2', to='strategy.StepImage')),
            ],
            options={
                'verbose_name': 'regression',
                'verbose_name_plural': 'regressions',
            },
        ),
    ]
