# Generated by Django 2.1.7 on 2019-04-27 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0020_vrttest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vrttest',
            options={'ordering': ['-create_at'], 'verbose_name': 'regression', 'verbose_name_plural': 'regressions'},
        ),
        migrations.AddField(
            model_name='vrttest',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
